import * as vscode from 'vscode';
import * as crypto from 'crypto';
import { ProvenanceStore } from '../storage/ProvenanceStore';

interface ChangeMetrics {
  speed: number;
  size: number;
  isBlock: boolean;
  isTabCompletion: boolean;
  timestamp: number;
}

export class AIBehaviorDetector {
  private changeHistory = new Map<string, ChangeMetrics[]>();
  private outputChannel: vscode.OutputChannel;
  private store: ProvenanceStore | null = null;
  private readonly AI_SPEED_THRESHOLD = 1000;
  private readonly AI_BLOCK_SIZE = 50;
  private readonly TAB_COMPLETION_SPEED = 100; // Very fast insertions
  private readonly TAB_COMPLETION_MAX_SIZE = 80; // Typically small snippets

  constructor(store?: ProvenanceStore) {
    this.outputChannel = vscode.window.createOutputChannel('Code Provenance');
    this.store = store || null;
  }

  setStore(store: ProvenanceStore): void {
    this.store = store;
  }

  start(): vscode.Disposable {
    return vscode.workspace.onDidChangeTextDocument((event) => {
      this.analyzeChange(event);
    });
  }

  private shouldIgnoreDocument(document: vscode.TextDocument): boolean {
    const uri = document.uri.toString();
    
    if (uri.includes('extension-output-')) return true;
    if (uri.includes('output:')) return true;
    if (document.languageId === 'Log') return true;
    if (document.languageId === 'log') return true;
    
    return false;
  }

  private analyzeChange(event: vscode.TextDocumentChangeEvent): void {
    if (event.contentChanges.length === 0) return;

    const uri = event.document.uri.toString();
    
    if (this.shouldIgnoreDocument(event.document)) return;

    const now = Date.now();

    for (const change of event.contentChanges) {
      const speed = this.calculateSpeed(uri, now);
      const metrics: ChangeMetrics = {
        speed: speed,
        size: change.text.length,
        isBlock: this.isBlockCompletion(change),
        isTabCompletion: this.isTabCompletion(change, speed),
        timestamp: now
      };

      this.recordChange(uri, metrics);

      if (this.isAIGenerated(metrics, change.text)) {
        this.captureProvenance(event, change, metrics);
      }
    }
  }

  private calculateSpeed(uri: string, now: number): number {
    const history = this.changeHistory.get(uri) || [];
    if (history.length === 0) return 0;

    const lastChange = history[history.length - 1];
    return now - lastChange.timestamp;
  }

  private isBlockCompletion(change: vscode.TextDocumentContentChangeEvent): boolean {
    const lines = change.text.split('\n').length;
    return lines > 3 || change.text.length > this.AI_BLOCK_SIZE;
  }

  private isTabCompletion(change: vscode.TextDocumentContentChangeEvent, speed: number): boolean {
    // Tab completions are typically:
    // 1. Very fast (< 100ms)
    // 2. Small to medium size (< 80 chars)
    // 3. Single line or simple multi-line
    // 4. Complete tokens (not partial words)
    
    if (speed > this.TAB_COMPLETION_SPEED) return false;
    if (change.text.length > this.TAB_COMPLETION_MAX_SIZE) return false;
    
    const lines = change.text.split('\n');
    if (lines.length > 5) return false; // Tab completions rarely exceed 5 lines
    
    // Check for complete tokens (not typing mid-word)
    const hasCompleteTokens = /^[\s\w]+$/.test(change.text) ||
                              /[({[\s]$/.test(change.text) ||
                              /^(const|let|var|function|class|if|for|while|return)\s/.test(change.text);
    
    return hasCompleteTokens;
  }

  private recordChange(uri: string, metrics: ChangeMetrics): void {
    const history = this.changeHistory.get(uri) || [];
    history.push(metrics);
    
    if (history.length > 10) {
      history.shift();
    }
    
    this.changeHistory.set(uri, history);
  }

  private isAIGenerated(metrics: ChangeMetrics, text: string): boolean {
    // Lower threshold for tab completions
    if (text.length < 10 && !metrics.isTabCompletion) return false;

    const indicators = [
      metrics.speed < this.AI_SPEED_THRESHOLD && metrics.size > 50,
      metrics.isBlock && text.includes('\n'),
      metrics.isTabCompletion, // Tab completion is a strong indicator
      this.hasAISignature(text),
      this.isStructuredCode(text)
    ];

    // Need at least 2 indicators, or 1 if it's tab completion + something else
    const indicatorCount = indicators.filter(Boolean).length;
    return indicatorCount >= 2 || (metrics.isTabCompletion && indicatorCount >= 1);
  }

  private hasAISignature(text: string): boolean {
    const signatures = [
      /\/\/.*Made with (Bob|AI|Copilot|Cursor|Windsurf)/i,
      /\/\/.*Generated by/i,
      /\/\/.*AI-generated/i,
      /#.*Made with (Bob|AI|Copilot|Cursor|Windsurf)/i,
      /#.*Generated by/i
    ];

    return signatures.some(sig => sig.test(text));
  }

  private isStructuredCode(text: string): boolean {
    const jsPatterns = [
      /function\s+\w+\s*\([^)]*\)\s*{/,
      /const\s+\w+\s*=\s*\([^)]*\)\s*=>/,
      /class\s+\w+\s*{/,
      /export\s+(default\s+)?(function|class|const)/
    ];

    const pyPatterns = [
      /def\s+\w+\s*\([^)]*\)\s*:/,
      /class\s+\w+(\([^)]*\))?\s*:/,
      /async\s+def\s+\w+/,
      /@\w+\s*\n\s*def/
    ];

    const allPatterns = [...jsPatterns, ...pyPatterns];
    return allPatterns.some(pattern => pattern.test(text));
  }

  private async captureProvenance(
    event: vscode.TextDocumentChangeEvent,
    change: vscode.TextDocumentContentChangeEvent,
    metrics: ChangeMetrics
  ): Promise<void> {
    const filePath = vscode.workspace.asRelativePath(event.document.uri);
    const startLine = change.range.start.line + 1;
    const endLine = change.range.end.line + 1;
    const language = event.document.languageId;
    const confidence = this.calculateConfidence(metrics, change.text);
    const riskLevel = this.assessRiskLevel(change.text);
    
    const provenance = {
      file: filePath,
      language: language,
      lines: `${startLine}-${endLine}`,
      size: change.text.length,
      hash: this.hashCode(change.text),
      timestamp: new Date().toISOString(),
      detection: {
        speed_ms: metrics.speed,
        is_block: metrics.isBlock,
        is_tab_completion: metrics.isTabCompletion,
        confidence: confidence
      }
    };

    // Store in provenance database
    if (this.store) {
      this.store.addRecord({
        file: filePath,
        language: language,
        lineRange: [startLine, endLine],
        code: change.text,
        codeHash: this.hashCode(change.text),
        detection: {
          speed_ms: metrics.speed,
          is_block: metrics.isBlock,
          is_tab_completion: metrics.isTabCompletion,
          confidence: confidence
        },
        compliance: {
          flags: this.detectComplianceFlags(change.text),
          risk_level: riskLevel,
          human_review_required: this.requiresHumanReview(change.text)
        },
        model: {
          name: 'Unknown',
          version: '1.0',
          provider: 'Detected'
        }
      });
    }

    this.outputChannel.appendLine('='.repeat(60));
    this.outputChannel.appendLine('AI CODE DETECTED');
    this.outputChannel.appendLine('='.repeat(60));
    this.outputChannel.appendLine(`File: ${provenance.file}`);
    this.outputChannel.appendLine(`Language: ${provenance.language}`);
    this.outputChannel.appendLine(`Lines: ${provenance.lines}`);
    this.outputChannel.appendLine(`Size: ${provenance.size} characters`);
    this.outputChannel.appendLine(`Hash: ${provenance.hash}`);
    this.outputChannel.appendLine(`Timestamp: ${provenance.timestamp}`);
    this.outputChannel.appendLine(`Detection Speed: ${provenance.detection.speed_ms}ms`);
    this.outputChannel.appendLine(`Block Completion: ${provenance.detection.is_block}`);
    this.outputChannel.appendLine(`Tab Completion: ${provenance.detection.is_tab_completion}`);
    this.outputChannel.appendLine(`Confidence: ${provenance.detection.confidence}%`);
    this.outputChannel.appendLine(`Risk Level: ${riskLevel}`);
    this.outputChannel.appendLine('');

    vscode.window.showInformationMessage(
      `AI code detected: ${filePath} (${provenance.lines}) - ${provenance.detection.confidence}% confidence`
    );
  }

  private detectComplianceFlags(code: string): string[] {
    const flags: string[] = [];
    
    if (/patient|medical|health|phi/i.test(code)) flags.push('HIPAA');
    if (/payment|credit|card|billing/i.test(code)) flags.push('PCI-DSS');
    if (/personal|privacy|consent|gdpr/i.test(code)) flags.push('GDPR');
    if (/sox|financial|audit/i.test(code)) flags.push('SOX');

    return flags;
  }

  private requiresHumanReview(code: string): boolean {
    return /auth|login|password|token|encrypt|decrypt|payment|security/i.test(code);
  }

  private assessRiskLevel(code: string): 'low' | 'medium' | 'high' | 'critical' {
    if (/password|secret|private.*key|api.*key/i.test(code)) return 'critical';
    if (/auth|login|payment|encrypt/i.test(code)) return 'high';
    if (/database|sql|query|api/i.test(code)) return 'medium';
    return 'low';
  }

  private calculateConfidence(metrics: ChangeMetrics, text: string): number {
    let confidence = 0;

    // Tab completion detection (30% confidence)
    if (metrics.isTabCompletion) {
      confidence += 30;
      
      // Boost confidence if it's a rapid series of tab completions
      if (metrics.speed < 50) confidence += 10; // Very rapid = likely AI
    }

    // Block completion (35% confidence)
    if (metrics.isBlock) confidence += 35;
    
    // Speed + size heuristic (30% confidence for large, fast insertions)
    if (metrics.speed < this.AI_SPEED_THRESHOLD && metrics.size > 50) confidence += 30;
    
    // AI signature in comments (5% confidence)
    if (this.hasAISignature(text)) confidence += 5;
    
    // Structured code patterns (20% confidence)
    if (this.isStructuredCode(text)) confidence += 20;

    return Math.min(confidence, 100);
  }

  private hashCode(text: string): string {
    return crypto.createHash('sha256').update(text).digest('hex').substring(0, 16);
  }
}

// Made with Bob
